github:
  users:
    url: https://api.github.com/users/
spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
